---
# Certificates for Puppet Infrastructure
# 
# IMPORTANT: Let's Encrypt Certificate Strategy
# ============================================
# Let's Encrypt can ONLY issue certificates for:
# - Publicly resolvable domain names (puppet.yourdomain.com)
# - Domains you control via DNS validation
# 
# Let's Encrypt CANNOT issue for:
# - Internal cluster DNS (.svc.cluster.local)
# - Private networks (10.0.0.0/8, 192.168.0.0/16)
# - .local, .internal domains
# 
# Strategy:
# 1. Public Puppet Server: letsencrypt-prod (puppet.yourdomain.com)
# 2. Internal services: selfsigned-issuer (PuppetDB, Puppetboard internal access)
# 3. Puppet agents: Use Puppet's internal PKI (handled by Puppet itself)

#############################################
# Certificate for PUBLIC Puppet Server
#############################################
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: puppet-server-public-cert
  namespace: puppet
spec:
  secretName: puppet-server-public-tls
  
  # Use Let's Encrypt for public-facing Puppet Server
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  
  # ONLY public domain names
  dnsNames:
    - puppet.yourdomain.com  # CHANGE THIS to your actual public domain!
  
  # For HTTPS/TLS termination at ingress
  usages:
    - digital signature
    - key encipherment
    - server auth
  
  # DNS validation (recommended for production)
  # Requires DNS01 solver configured in letsencrypt-prod ClusterIssuer
  # Alternative: HTTP01 validation
  
  # Renewal settings
  renewBefore: 720h  # 30 days

---
#############################################
# Certificate for Puppetboard (Internal Web UI)
#############################################
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: puppetboard-cert
  namespace: puppet
spec:
  secretName: puppetboard-tls
  
  # Use self-signed for internal services
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  
  # Can use internal DNS names with self-signed
  dnsNames:
    - puppetboard.puppet.svc.cluster.local
    - puppetboard.yourdomain.internal  # CHANGE if you have internal DNS
  
  usages:
    - digital signature
    - key encipherment
    - server auth
  
  duration: 8760h  # 1 year
  renewBefore: 720h

---
#############################################
# Certificate for PuppetDB API (Internal)
#############################################
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: puppetdb-api-cert
  namespace: puppet
spec:
  secretName: puppetdb-api-tls
  
  # Use self-signed for internal API access
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  
  dnsNames:
    - puppetdb.puppet.svc.cluster.local
    - puppetdb.yourdomain.internal  # CHANGE if you have internal DNS
  
  usages:
    - digital signature
    - key encipherment
    - server auth
  
  duration: 8760h
  renewBefore: 720h

---
#############################################
# IMPORTANT NOTES
#############################################
# 
# 1. PUPPET AGENT CERTIFICATES:
#    - Puppet has its own internal PKI
#    - Agent certificates are managed by Puppet, not cert-manager
#    - Agents connect to port 8140 with SSL passthrough
#    - DO NOT try to use Let's Encrypt/cert-manager for agent certs!
# 
# 2. LET'S ENCRYPT REQUIREMENTS:
#    - Your DNS must be publicly resolvable
#    - You must prove domain ownership via DNS01 or HTTP01 challenge
#    - Ensure your letsencrypt-prod ClusterIssuer is properly configured
# 
# 3. INTERNAL SERVICES:
#    - Use selfsigned-issuer for services only accessed internally
#    - Puppetboard and PuppetDB API typically only need internal access
# 
# 4. IF YOU DON'T HAVE PUBLIC DNS:
#    - Use selfsigned-issuer for ALL certificates
#    - Change puppet-server-public-cert to use selfsigned-issuer
#    - Accept self-signed certificate warnings in browsers
# 
# Example ClusterIssuer configuration (should already exist):
# 
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-prod
# spec:
#   acme:
#     server: https://acme-v02.api.letsencrypt.org/directory
#     email: admin@yourdomain.com  # CHANGE THIS
#     privateKeySecretRef:
#       name: letsencrypt-prod-key
#     solvers:
#       - dns01:  # Recommended for wildcard certs
#           cloudflare:  # Or your DNS provider
#             apiTokenSecretRef:
#               name: cloudflare-api-token
#               key: api-token
#       # OR
#       - http01:  # For single domain validation
#           ingress:
#             class: traefik
