---
# PostgreSQL Database Initialization Job
# 
# This Job creates the puppetdb database and user in your external PostgreSQL
# Run once before deploying Puppet Server
# 
# SECURITY NOTE: This is a one-time setup job
# Delete after successful execution or use InitContainer pattern

apiVersion: batch/v1
kind: Job
metadata:
  name: puppetdb-init-db
  namespace: puppet
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "0"  # Run before everything else
spec:
  ttlSecondsAfterFinished: 600  # Auto-cleanup after 10 minutes
  backoffLimit: 3
  
  template:
    metadata:
      name: puppetdb-init-db
    spec:
      restartPolicy: OnFailure
      
      containers:
        - name: init-db
          image: postgres:16-alpine
          
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "Connecting to PostgreSQL at $POSTGRES_HOST:$POSTGRES_PORT..."
              
              # Wait for PostgreSQL to be ready
              until pg_isready -h "$POSTGRES_HOST" -p "$POSTGRES_PORT" -U "$POSTGRES_ADMIN_USER"; do
                echo "Waiting for PostgreSQL to be ready..."
                sleep 2
              done
              
              echo "PostgreSQL is ready. Creating database and user..."
              
              # Create database and user
              PGPASSWORD="$POSTGRES_ADMIN_PASSWORD" psql \
                -h "$POSTGRES_HOST" \
                -p "$POSTGRES_PORT" \
                -U "$POSTGRES_ADMIN_USER" \
                -d postgres \
                <<-EOSQL
                  -- Create user if not exists
                  DO \$\$
                  BEGIN
                    IF NOT EXISTS (SELECT FROM pg_user WHERE usename = '$PUPPETDB_USER') THEN
                      CREATE USER $PUPPETDB_USER WITH PASSWORD '$PUPPETDB_PASSWORD';
                    END IF;
                  END
                  \$\$;
                  
                  -- Create database if not exists
                  SELECT 'CREATE DATABASE $PUPPETDB_DATABASE OWNER $PUPPETDB_USER'
                  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$PUPPETDB_DATABASE')\gexec
                  
                  -- Grant privileges
                  GRANT ALL PRIVILEGES ON DATABASE $PUPPETDB_DATABASE TO $PUPPETDB_USER;
                  
                  -- Connect to puppetdb database and set up extensions
                  \c $PUPPETDB_DATABASE
                  
                  -- Grant schema privileges
                  GRANT ALL ON SCHEMA public TO $PUPPETDB_USER;
                  
                  -- PuppetDB requires pg_trgm extension for performance
                  CREATE EXTENSION IF NOT EXISTS pg_trgm;
                  
                  -- Optional: pgcrypto for advanced features
                  CREATE EXTENSION IF NOT EXISTS pgcrypto;
              EOSQL
              
              echo "Database setup completed successfully!"
              
          env:
            # PostgreSQL connection details
            - name: POSTGRES_HOST
              value: "postgresql.default.svc.cluster.local"  # CHANGE THIS!
            - name: POSTGRES_PORT
              value: "5432"
            
            # Admin credentials (for creating database)
            - name: POSTGRES_ADMIN_USER
              value: "postgres"  # CHANGE if different
            - name: POSTGRES_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-admin-secret  # CHANGE to your admin secret name
                  key: password
            
            # PuppetDB database settings
            - name: PUPPETDB_DATABASE
              value: "puppetdb"
            - name: PUPPETDB_USER
              valueFrom:
                secretKeyRef:
                  name: puppetdb-postgres-secret
                  key: username
            - name: PUPPETDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: puppetdb-postgres-secret
                  key: password

---
#############################################
# Alternative: InitContainer Pattern
#############################################
# If you prefer, add this to PuppetDB StatefulSet as initContainer
# This ensures database is ready before PuppetDB starts
#
# Add to puppet-server/values.yaml:
#
# puppetdb:
#   initContainers:
#     - name: wait-for-db
#       image: postgres:16-alpine
#       command:
#         - /bin/sh
#         - -c
#         - |
#           until pg_isready -h "$PUPPETDB_POSTGRES_HOSTNAME" -p 5432 -U "$PUPPETDB_POSTGRES_USERNAME"; do
#             echo "Waiting for PostgreSQL..."
#             sleep 2
#           done
#           echo "PostgreSQL is ready!"
#       env:
#         - name: PUPPETDB_POSTGRES_HOSTNAME
#           value: "postgresql.default.svc.cluster.local"
#         - name: PUPPETDB_POSTGRES_USERNAME
#           valueFrom:
#             secretKeyRef:
#               name: puppetdb-postgres-secret
#               key: username

---
#############################################
# IMPORTANT NOTES
#############################################
#
# 1. SECRETS REQUIRED:
#    - postgresql-admin-secret: Admin credentials for creating database
#    - puppetdb-postgres-secret: PuppetDB user credentials
#
# 2. ARGOCD HOOKS:
#    - PreSync: Runs before main deployment
#    - HookSucceeded: Deletes job after success
#
# 3. MANUAL EXECUTION (if not using ArgoCD hooks):
#    kubectl apply -f puppet-server/templates/postgres-init-job.yaml
#    kubectl wait --for=condition=complete --timeout=300s job/puppetdb-init-db -n puppet
#
# 4. TROUBLESHOOTING:
#    kubectl logs -n puppet job/puppetdb-init-db
#
# 5. PRODUCTION CONSIDERATIONS:
#    - Use a secrets management solution for admin password
#    - Consider using database operators (CloudNativePG, Zalando Postgres)
#    - Implement proper backup strategy
#    - Use connection pooling (PgBouncer) for production scale
