---
# PostgreSQL Credentials Secret
# OPTION 1: Use SealedSecret (recommended)
# OPTION 2: Use External Secrets Operator
# OPTION 3: Manual secret (for testing only - DO NOT commit to Git!)

# ==========================================
# OPTION 1: SealedSecret (Recommended)
# ==========================================
# Install: kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.0/controller.yaml
#
# Create and seal the secret:
# kubectl create secret generic puppetdb-postgres-secret \
#   --namespace puppet \
#   --from-literal=username=puppetdb \
#   --from-literal=password='YOUR_SECURE_PASSWORD' \
#   --dry-run=client -o yaml | \
#   kubeseal -o yaml > puppet-server/templates/postgres-secret.yaml
######### preffered mathod for production
# apiVersion: bitnami.com/v1alpha1
# kind: SealedSecret
# metadata:
#   name: puppetdb-postgres-secret
#   namespace: puppet
# spec:
#   encryptedData:
#     username: SEALED_DATA_HERE  # Replace with sealed data
#     password: SEALED_DATA_HERE  # Replace with sealed data
#   template:
#     metadata:
#       name: puppetdb-postgres-secret
#       namespace: puppet
#     type: Opaque

---
# ==========================================
# OPTION 2: External Secrets Operator
# ==========================================
# Requires: External Secrets Operator installed
# Store credentials in: AWS Secrets Manager, HashiCorp Vault, Azure Key Vault, etc.

# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: puppetdb-postgres-secret
#   namespace: puppet
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: vault-backend  # Your SecretStore
#     kind: ClusterSecretStore
#   target:
#     name: puppetdb-postgres-secret
#     creationPolicy: Owner
#   data:
#     - secretKey: username
#       remoteRef:
#         key: puppet/postgres
#         property: username
#     - secretKey: password
#       remoteRef:
#         key: puppet/postgres
#         property: password

---
# ==========================================
# OPTION 3: Plain Secret (Testing ONLY)
# ==========================================
# WARNING: NEVER commit this to Git with real credentials!
# For testing only - use SealedSecret or External Secrets in production

apiVersion: v1
kind: Secret
metadata:
  name: puppetdb-postgres-secret
  namespace: puppet
type: Opaque
stringData:
  username: "{ .Values.additions.postgres.user }"
  password: "{ . Values.additions.postgres.password }"  # CHANGE THIS!

---
# r10k SSH Key Secret
# Generate SSH key:
# ssh-keygen -t ed25519 -C "r10k@puppet-server" -f r10k-key -N ""
#
# Then seal it:
# kubectl create secret generic r10k-ssh-key \
#   --namespace puppet \
#   --from-file=id-control_repo.rsa=r10k-key \
#   --from-file=id-control_repo.rsa.pub=r10k-key.pub \
#   --dry-run=client -o yaml | \
#   kubeseal -o yaml > puppet-server/templates/r10k-secret.yaml

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: r10k-ssh-key
  namespace: puppet
spec:
  encryptedData:
    id-control_repo.rsa: SEALED_DATA_HERE      # Replace with sealed data
    id-control_repo.rsa.pub: SEALED_DATA_HERE  # Replace with sealed data
  template:
    metadata:
      name: r10k-ssh-key
      namespace: puppet
    type: Opaque
